# <span style="color:Green">Комментарий от наставника</span>

Привет, это снова Дмитрий, наставник в твоей группе. Поздравляю с преодолением первых двух модулей и началу знакомства с математикой DS. Это должно быть увлекательным!

---

<span style="color:Green">

**2020-01-21 DD**



</span>

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## 1. Загрузка данных

In [14]:
import pandas as pd
import numpy as np
from pathlib import Path
path = Path.cwd()

In [15]:
df = pd.read_csv('{}/datasets/insurance.csv'.format(path), index_col=0)
df.columns = ['sex', 'age', 'income', 'family', 'insurance']

In [16]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   sex        5000 non-null   int64  
 1   age        5000 non-null   float64
 2   income     5000 non-null   float64
 3   family     5000 non-null   int64  
 4   insurance  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 234.4 KB
None
               sex          age        income       family    insurance
count  5000.000000  5000.000000   5000.000000  5000.000000  5000.000000
mean      0.499000    30.952800  39916.360000     1.194200     0.148000
std       0.500049     8.440807   9900.083569     1.091387     0.463183
min       0.000000    18.000000   5300.000000     0.000000     0.000000
25%       0.000000    24.000000  33300.000000     0.000000     0.000000
50%       0.000000    30.000000  40200.000000     1.000000     0.000000
75%       1.000000    37.000000  46600.000000     2.0

Данные без пропусков, распределены нормально. Возраст от 18 до 65. Зарплата от 5300 до 79000. Членов семьи максимум 6, страховых выплат - 5

## 2. Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** не изменится

**Обоснование:**
Посмотрим к чему мы придем умножив X на обратимую матрицу A<br>
Учитывая, что $ (ABC)^{-1} = C^{-1}B^{-1}A^{-1} $ и $ (AB)^T = B^T A^T $ <br><br>
$$
w_A = ((X A)^T (X A))^{-1} (X A)^T y = (A^T X^T X A)^{-1} A^T X^T y = A^{-1} X^{-1} (X^T)^{-1} (A^T)^{-1} A^T X^T y = ...
$$<br>
Так как матрица A обратимая, то $ (A^T)^{-1} A^T = E $ и:<br><br>
$$
... = A^{-1} X^{-1} (X^T)^{-1} E  X^T y = A^{-1} (X^T X)^{-1} X^T y = A^{-1} w
$$

Получается, что если мы умножим исходные параметры на обратимую матрицу, то параметры линейной регрессии просто умножатся на обратную матрицу

<span style="color:Green">

**2020-01-21 DD**

Ответ - верный. Если мы выполняем линейные преобразования при помощи обратимой матрицы, то мы не теряем ни информацию, ни, тем более, не выходим за рамки применимости линейной алгебры для "обучения" модели; просто меняем "базис" пространства (признаков), что приводит к изменению значений коэффициентов $w$, но не к порядкам отношений между этими коэффициентами.

Стало быть, если у нас есть обратимая матрица $A$, то от $Xw$ можно перейти к $XAw=Xw_A$.

Рассуждения - в верном русле, но есть три момента:
- (принципиальный) в явном виде не показано, почему всё-таки при таком преобразовании качество модели (по метрике $R^2$) не меняется,
- (технический) мне думается, что ты внёс некоторую громоздкость в изложение, положившись на свойства раскрытия скобок для произведений матриц.

Итак, как у нас связаны $w$ и $w_A$? Очевидно, что 

$$w_A=A^{-1}w$$
$$w=Aw_A$$

Но почему тогда значение $R^2$ у нас будет *одинаковым*? Попробуй подумать над этим моментом. Подсказка, как я вижу всё это: $R^2$ зависит от исходных значений целевого признака и прогнозных значений целевого признака. По сути, следует аналитически (на формулах) показать, что применение трансформации при помощи А не изменит прогнозные значения целевого признака.

Если не будет получаться аналитически, то можно просто пояснить словами.

</span>

#### 2020-01-22
Спасибо за разъяснения!<br>
1. Я выкладками пытался как раз показать что $ w_A = A^{-1} w $ , для меня это было не очевидно
2. Показать что предсказанные значения не изменятся не сложно:<br><br>
$$
a_A = X_A w_A = X A A^{-1} w = X E w = X w = a
$$<br>
Ну а раз предсказанные значения не изменятся, то и $R^2$ не поменятся!

<span style="color:Green">

**2020-01-22 DD**

Верно! Прогнозные значения не меняются, хотя мы поменяли входные данные. Ну, разве это не есть небольшое волшебство математики? ) 

</span>

## 3. Алгоритм преобразования

**Алгоритм**

* рассчитаем параметры линейной регрессии w и r2_score для исходных данных
* сгенерируем матрицу A и обратную к ней матрицу $A^{-1}$
* умножим исходные данные df на A
* рассчитаем параметры линейной регрессии $ w_a $ и  r2_score для преобразованных данных
* проверим что $ w_a = A^{-1} w $ и сравним два значения r2_score


**Обоснование**

...

## 4. Проверка алгоритма

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

features = df.drop(['insurance'], axis=1)
target = df['insurance']

model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)

print('Предсказания модели: {}'.format(predictions))
print('R2_score {:.4f}'.format(r2_score(target, predictions)))



Предсказания модели: [ 0.51172715  0.68431581  0.09373365 ... -0.25697046 -0.19099161
  0.04904991]
R2_score 0.4249


In [18]:
from numpy.linalg import inv 

def conversion(features):
    conv_matrix = np.random.rand(features.shape[1], features.shape[1])
    features = features @ conv_matrix
    return features, conv_matrix

features = df.drop(['insurance'], axis=1)
target = df['insurance']

features, conv_matrix = conversion(features)

model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print('Предсказания модели после преобразования: {}'.format(predictions))
print('R2_score {:.4f}'.format(r2_score(target, predictions)))

print('Матрица преобразований:')
print(conv_matrix)




Предсказания модели после преобразования: [ 0.51172715  0.68431581  0.09373365 ... -0.25697046 -0.19099161
  0.04904991]
R2_score 0.4249
Матрица преобразований:
[[0.86977855 0.79486714 0.40005891 0.01987717]
 [0.77862246 0.85329123 0.53841801 0.72121426]
 [0.50702987 0.65928467 0.90485281 0.48353919]
 [0.63522737 0.7759846  0.64020328 0.46050999]]


Убедимся что преобразование обратимое

In [19]:
features = df.drop(['insurance'], axis=1)
print('Исходные данные')
print(features)
features, conv_matrix = conversion(features)
print('Преобразованные данные')
print(features)
print('Данные после обратного преобразования')
features = features @ inv(conv_matrix)
print(features.round())

Исходные данные
      sex   age   income  family
0       1  41.0  49600.0       1
1       0  46.0  38000.0       1
2       0  29.0  21000.0       0
3       0  21.0  41700.0       2
4       1  28.0  26100.0       0
...   ...   ...      ...     ...
4995    0  28.0  35700.0       2
4996    0  34.0  52400.0       1
4997    0  20.0  33900.0       2
4998    1  22.0  32700.0       3
4999    1  28.0  40600.0       1

[5000 rows x 4 columns]
Преобразованные данные
                 0             1             2             3
0     29207.166018  16611.801784  12913.142705  33552.592805
1     22386.545462  12731.230308   9894.663506  25715.782243
2     12374.092524   7036.335202   5468.190427  14213.364551
3     24545.027494  13962.823687  10855.204225  28199.547479
4     15373.995955   8742.812738   6795.641721  17660.054778
...            ...           ...           ...           ...
4995  21020.597373  11956.941310   9294.639588  24149.487700
4996  30848.639772  17546.760817  13640.576169  3543

R2_score в обоих случаях совпали. Выше в формулах у меня выходило что коэффициенты линейной модели будут отличаться на $A^{-1}$, но даже по размерности видно что это невозможно. Так и не нашел где я ошибаюсь в формулах :( Матричное преобразования вообще никак не повлияло на коэффициенты $ w $


<span style="color:Green">

**2020-01-21 DD**

$R^2$ будет одинаковым. Коэффициенты будут отличаться, попробуй выведи model.coef_ для обоих моделей и покажи, что при помощи $A$ их действительно можно переводить друг в друга.

</span>

#### 2020-01-22
Выше я написал что "Матричное преобразования вообще никак не повлияло на коэффициенты  𝑤", но конечно же код показывает, что преобразование не повлияло на значения предсказания модели, а не на коэффициенты! Коэффициенты поменялись, ниже пример

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

features = df.drop(['insurance'], axis=1)
target = df['insurance']

model = LinearRegression()
model.fit(features, target)
print('Исходные коэффициенты модели линейной регрессии: {}'.format(model.coef_))

features, conv_matrix = conversion(features)

model = LinearRegression()
model.fit(features, target)

print('Коэффициенты модели линейной регрессии после преобразования: {}'.format(model.coef_))
print('Коэффициенты модели линейной регрессии после обратного преобразования: {}'.format(conv_matrix @ model.coef_))

Исходные коэффициенты модели линейной регрессии: [ 7.92580543e-03  3.57083050e-02 -1.70080492e-07 -1.35676623e-02]
Коэффициенты модели линейной регрессии после преобразования: [ 0.56856723  0.24529404 -0.44697005 -0.66618952]
Коэффициенты модели линейной регрессии после обратного преобразования: [ 7.92580543e-03  3.57083050e-02 -1.70080491e-07 -1.35676623e-02]


### После обратного преобразования коэффициенты равны исходным!

<span style="color:Green">

**2020-01-22 DD**

Отлично. Спасибо за доработку проекта! Принимается.

</span>

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [ ]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования